/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ButtonBlue: typeof import('./src/components/general/button/ButtonBlue.vue')['default']
    CreateTime: typeof import('./src/components/general/time/CreateTime.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Footer: typeof import('./src/components/index/Footer.vue')['default']
    Header: typeof import('./src/components/index/Header.vue')['default']
    HeaderItem: typeof import('./src/components/index/components/HeaderItem.vue')['default']
    HorizontalTable: typeof import('./src/components/general/table/HorizontalTable.vue')['default']
    Image: typeof import('./src/components/general/image/Image.vue')['default']
    Input: typeof import('./src/components/general/input/Input.vue')['default']
    InterfaceCard: typeof import('./src/components/content/interface/card/InterfaceCard.vue')['default']
    InterfaceInput: typeof import('./src/components/general/input/InterfaceInput.vue')['default']
    Pagination: typeof import('./src/components/general/page/Pagination.vue')['default']
    ResultDisplay: typeof import('./src/components/general/display/ResultDisplay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollTitle: typeof import('./src/components/general/titile/ScrollTitle.vue')['default']
    SideMenu: typeof import('./src/components/general/menu/SideMenu.vue')['default']
    Tip: typeof import('./src/components/popup/Tip.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
