/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArticleItem: typeof import('./src/components/content/article/ArticleItem.vue')['default']
    ArticleList: typeof import('./src/components/content/article/ArticleList.vue')['default']
    ButtonBlue: typeof import('./src/components/general/button/ButtonBlue.vue')['default']
    Comment: typeof import('./src/components/content/comment/Comment.vue')['default']
    CommentInput: typeof import('./src/components/content/comment/components/CommentInput.vue')['default']
    CreateTime: typeof import('./src/components/general/time/CreateTime.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    Emoji: typeof import('./src/components/general/emoji/Emoji.vue')['default']
    EmojiInput: typeof import('./src/components/general/input/EmojiInput.vue')['default']
    Footer: typeof import('./src/components/index/Footer.vue')['default']
    Header: typeof import('./src/components/index/Header.vue')['default']
    Header1: typeof import('./src/components/index/Header1.vue')['default']
    HeaderItem: typeof import('./src/components/index/components/HeaderItem.vue')['default']
    HomeItem: typeof import('./src/components/content/home/HomeItem.vue')['default']
    HomeList: typeof import('./src/components/content/home/HomeList.vue')['default']
    HorizontalTable: typeof import('./src/components/general/table/HorizontalTable.vue')['default']
    Image: typeof import('./src/components/general/image/Image.vue')['default']
    InterfaceCard: typeof import('./src/components/content/interface/card/InterfaceCard.vue')['default']
    InterfaceInput: typeof import('./src/components/general/input/InterfaceInput.vue')['default']
    Load: typeof import('./src/components/popup/Load.vue')['default']
    PageCover: typeof import('./src/components/general/page-cover/PageCover.vue')['default']
    Pagination: typeof import('./src/components/general/page/Pagination.vue')['default']
    Paging: typeof import('./src/components/general/page/Paging.vue')['default']
    ReplyInput: typeof import('./src/components/content/comment/components/ReplyInput.vue')['default']
    ResultDisplay: typeof import('./src/components/general/display/ResultDisplay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollTitle: typeof import('./src/components/general/titile/ScrollTitle.vue')['default']
    SideMenu: typeof import('./src/components/general/menu/SideMenu.vue')['default']
    SvgIcon: typeof import('./src/components/general/icon/SvgIcon.vue')['default']
    TalkItem: typeof import('./src/components/content/talk/TalkItem.vue')['default']
    TalkList: typeof import('./src/components/content/talk/TalkList.vue')['default']
    TalkMd: typeof import('./src/components/content/talk/TalkMd.vue')['default']
    Tip: typeof import('./src/components/popup/Tip.vue')['default']
    Tools: typeof import('./src/components/Tools.vue')['default']
    Wait: typeof import('./src/components/popup/Wait.vue')['default']
  }
}
